export const classEnrollmentData = [
  { class: 'Class 1', students: 27 },
  { class: 'Class 2', students: 32 },
  { class: 'Class 3', students: 29 },
  { class: 'Class 4', students: 31 },
  { class: 'Class 5', students: 28 },
  { class: 'Class 6', students: 33 },
  { class: 'Class 7', students: 30 },
  { class: 'Class 8', students: 35 },
];

export const performanceData = [
  { name: 'Excellent (90-100%)', value: 45, color: '#22c55e' },
  { name: 'Good (80-89%)', value: 35, color: '#3b82f6' },
  { name: 'Average (70-79%)', value: 15, color: '#f59e0b' },
  { name: 'Needs Improvement', value: 5, color: '#ef4444' },
];

export const topStudents = [
  {
    rank: 1,
    name: 'Ahan Kumar',
    class: 'Class 8',
    points: 830,
    accuracy: 96,
    streak: 15,
    lessons: 68,
    avatar: 'AK',
  },
  {
    rank: 2,
    name: 'Hvff',
    class: 'Class 7',
    points: 295,
    accuracy: 94,
    streak: 12,
    lessons: 45,
    avatar: 'HV',
  },
  {
    rank: 3,
    name: 'Flower Girl',
    class: 'Class 6',
    points: 190,
    accuracy: 93,
    streak: 8,
    lessons: 38,
    avatar: 'FG',
  },
  {
    rank: 4,
    name: '12 June Child Test',
    class: 'Class 5',
    points: 165,
    accuracy: 92,
    streak: 6,
    lessons: 32,
    avatar: 'JC',
  },
  {
    rank: 5,
    name: 'Hcdff',
    class: 'Class 4',
    points: 160,
    accuracy: 91,
    streak: 5,
    lessons: 30,
    avatar: 'HC',
  },
  {
    rank: 6,
    name: 'Eva',
    class: 'Class 3',
    points: 145,
    accuracy: 90,
    streak: 4,
    lessons: 28,
    avatar: 'EV',
  },
  {
    rank: 7,
    name: 'Sophia Kim',
    class: 'Class 2',
    points: 138,
    accuracy: 89,
    streak: 7,
    lessons: 26,
    avatar: 'SK',
  },
  {
    rank: 8,
    name: 'James Wilson',
    class: 'Class 6',
    points: 132,
    accuracy: 88,
    streak: 3,
    lessons: 24,
    avatar: 'JW',
  },
  {
    rank: 9,
    name: 'Olivia Davis',
    class: 'Class 5',
    points: 128,
    accuracy: 87,
    streak: 9,
    lessons: 22,
    avatar: 'OD',
  },
  {
    rank: 10,
    name: 'Liam Garcia',
    class: 'Class 1',
    points: 120,
    accuracy: 86,
    streak: 2,
    lessons: 20,
    avatar: 'LG',
  },
];

export const allStudents = [
  ...topStudents,
  {
    rank: 11,
    name: 'Ava Martinez',
    class: 'Class 3',
    points: 100,
    accuracy: 85,
    streak: 1,
    lessons: 18,
    avatar: 'AM',
  },
  {
    rank: 12,
    name: 'Noah Thompson',
    class: 'Class 4',
    points: 95,
    accuracy: 83,
    streak: 3,
    lessons: 16,
    avatar: 'NT',
  },
];
